### ISSUE TITLE
Ansible is unable to import public signing key from rabbitmq.com due to user agent filtering

### ISSUE THREAD

**Issue by bluesalt** [rabbitmq/rabbitmq-server-release#53]
I attempted Ansible's `rpm_key` to import the rabbitmq signing key but received an 403 in CentOS 7.

```
- name: import rabbitmq key
  rpm_key:
    state: present
    key: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    validate_certs: yes
```

Here is excerpt of the response 

```
      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>The owner of this website (www.rabbitmq.com) has banned your access based on your browser's signature (3a6f38e19e0178a4-ua48).</p>
          </div>

          
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>3a6f38e19e0178a4</strong></span>
    
  </p>
```

I believe this is cause by the access rule about `User-Agent` because it is easy to reproduce the issue and Ansible rpm_key module does use `Python-urllib/2.7` as the `User-Agent`.

```
curl -v -H "User-Agent: Python-urllib/2.7"  https://www.rabbitmq.com/rabbitmq-release-signing-key.asc  # 403 forbidden

curl -v https://www.rabbitmq.com/rabbitmq-release-signing-key.asc # 200 ok
```

It is possible for you guys to allow that user-agent?
